### ISSUE TITLE
ran out of memory

### ISSUE THREAD

**Issue by dorje** [anishathalye/neural-style#21]
Hello Anish Athalye,

Thanks for sharing such great repo.
I met 'ran out of memory' issue when using TensorFLow 0.9 + Cuda 7.5 on a single Titan X card (12GB memory).

However, when I reduce the input image to size 100 pixel * 100 pixel, it works well, but as you can imagine, the output image is too small to see.

Any suggestions ?

Cheers,
Dorje

**Comment by anishathalye** [comment]
The larger the image, the more memory you need.

I've been able to get ~ 1000x1000 images to work on my Titan X.

**Comment by dorje** [comment]
What version did you use ? Was it TF 0.9 ?

I couldn't make it even with 200*200 images...... but it did work well when the images are just 100*100.

Any clue?

Cheers

**Comment by dorje** [comment]
OK, I guess I got the problem:
when running with GPU, the image should be square, like 900*900, NOT 900*700.

Cheers,
Dorje

**Comment by anishathalye** [comment]
It should work with non-square images too

**Comment by dorje** [comment]
Yes, you are right.
I just tried again. and it worked!
I don't know why it didn't work. Maybe there was something wrong in my OS at last day, I don't know.
But after shut down, and restart my PC, it worked.

So, please delete this issue for me after you read it. Thanks.

Cheers,
Dorje

**Comment by anishathalye** [comment]
awesome 👍
